### ISSUE TITLE
Interesting results of normalization

### ISSUE THREAD

**Issue by smith6jt-cop** [ColemanRHarris/mxnorm#13]
Hello,

I used the log10 with ComBat normalization method for analyzing 5 samples of spleen multiplex images.  I exported the mx_norm$norm_data and plotted in a MatLab program called Cytomap.  Does anyone know why there are stripes in the plot?
![image](https://github.com/ColemanRHarris/mxnorm/assets/73438963/ee783ed2-c2e2-4278-972e-4ab21da3736b)

**Comment by ColemanRHarris** [comment]
Hi @smith6jt-cop, these stripes are likely due to zero or near-zero values before the normalization that get forced to a less random set of values than the rest of the data. Please review your data as this is a result of the normalization algorithms themselves. For further reading, please see the following notes from our research:

- https://cran.r-project.org/web/packages/mxnorm/vignettes/mxnorm-vignette.html#mxnorm-implementation-of-combat
- https://academic.oup.com/bioinformatics/article/38/6/1700/6496920#394291495
