### ISSUE TITLE
Installation notes

### ISSUE THREAD

**Issue by tijeco** [ColemanRHarris/mxnorm#4]
I've tried installing mxnorm on a fresh environment. Here is what my setup was so that you have a better idea.

I'm using a freshly installed Linux container installed on a pixelbook (which is a docker container of a fairly bare bones Debian, I can provide the specific version if necessary). I installed miniconda, and made a separate environment for R using the following command (also installed mamba, because mamba is amazing):

```
mamba create -n R -c conda-forge r-base r-essentials 
``` 

Inside the R environment, I followed the instructions to install mxnorm ` install.packages("mxnorm")`

On my end, it gave an error that `lme4` and `nloptr` needed to be installed. I used the following command to get those installed through conda:

```
mamba install -c conda-forge r-lme4 r-nloptr
```

Now, my macbook already has a well established R environment setup, so I doubt I would have any problems installing it there, I just wanted to see how it would work on a fresh environment.

I just wanted to bring those dependencies to your attention. I think it should be a pretty easy thing to either include in the README or on CRAN setup side of things.

I also wanted to mention, in case you haven't considered it already, to at some point make mxnorm available through conda. It seems like it wouldn't be too difficult, and most of the dependencies should already be available through there.

**Comment by ColemanRHarris** [comment]
After doing some digging, it looks like both `lme4` (and `nloptr` since it's one of the dependencies) are not included in the `r-essentials` bundle from conda. `lme4` is listed as an "Import" in the `DESCRIPTION` file, so I would expect that R would either prompt you to install those packages or go ahead and install them by default when installing `mxnorm`. 

Can you share more info about the error you encountered? Was it the R environment flagging that you needed to install those packages, and instead of installing them within the R environment you installed them via `conda`?

**Comment by ColemanRHarris** [comment]
So I was able to setup a similar Docker container and re-create this issue, which turned out to be a missing dependency for `CMake` installed on the machine. I've added this to the [Dependencies](https://github.com/ColemanRHarris/mxnorm#dependencies) section of the README in case users hit the same error.
